turtlebot3: #namespace

    n_actions: 3 # We have 3 actions, Forwards,TurnLeft,TurnRight
    n_observations: 6 # We have 6 different observations

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 0.5 # Spwwed for ging fowards
    linear_turn_speed: 0.05 # Lienare speed when turning
    angular_speed: 0.3 # Angular speed when turning Left or Right
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    new_ranges: 24 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.2 # Minimum meters below wich we consider we have crashed
    max_laser_value: 6 # Value considered Ok, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed
    max_linear_aceleration: 5.0 # Linear acceleration value in which we consider Turtlebot 3 has crashed into something
    
    forwards_reward: 5 # Points Given to go forwards
    turn_reward: 1 # Points Given to turn as action
    end_episode_points: 200 # Points given when ending an episode

    max_goal_distance: 4.0
    easy_goal_thold: 0.75 #75%
    
    # New parameters for goal sampling
    goal_threshold: 0.25 # Distance to goal to consider we have reached it
    max_steps_per_episode: 800 # Maximum number of steps per episode

    # Rewards
    progress_rwd : 40       # Incentiva l'avvicinamento al goal
    collision_rwd : 2.0     # Penalità per la vicinanza agli ostacoli
    yaw_rwd : 1.0           # Incentivo per il direzionamento verso il goal
            
    terminal_goal_rwd: 50.0
    terminal_crash_rwd: -25.0
    terminal_timeout_rwd: -10.0

    time_rwd : -0.05 # Penalità temporale costante per ogni step

    # Training/Testing Phase
    mode: "train" # "train" o "test"
