turtlebot3: #namespace

    task_and_robot_environment_name: 'TurtleBot3World-v0'
    ros_ws_abspath: "/home/ubuntu/simulation_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #dqn parameters
    gamma: 0.999
    epsilon_start: 0.9
    epsilon_end: 0.05
    epsilon_decay: 5000
    n_episodes: 2000
    target_update: 10
    batch_size: 128
    lr: 1e-4
    optimizer: "RMSprop"

    max_step: 601
    running_step: 0.06 # Time for each step

    

